name: Deploy Production

on:
  push:
    branches:
    - production
    paths:
    - 'wp-content/themes/shiftr/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set-up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Get deps
      run: npm -s run install-theme-deps
    - name: Compile (minified)
      run: cd wp-content/themes/shiftr && NODE_ENV='production' gulp build
    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.PRODUCTION_DEPLOY_KEY}}
      with:
        flags: '-avzO --no-perms --delete'
        options: '--exclude-from $GITHUB_WORKSPACE/.workflow/exclude/deploy-production.txt'
        ssh_options: ''
        src: '${{ secrets.THEME_DIR }}'
        dest: '${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }}:${{ secrets.PRODUCTION_PATH }}/${{ secrets.THEME_DIR }}'